name: CI/CD Pipeline

on: [push]

job:
  tests:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x, 18.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
