name: CI/CD Pipeline

on: [push]

jobs:
  tests:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]
        test-type: ["unit", "integration"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          if ("${{ matrix.test-type }}" == "unit"); then
            npm run test:unit
          elif ("${{ matrix.test-type }}" == "integration"); then
            npm run test:integration
          else
            npm run test
          fi

        working-directory: ./test
